### ISSUE TITLE
Implement All Problems List View

### ISSUE THREAD

**Issue by harlsh** [harlsh/leechcode#7]
Design the following page
https://leetcode.com/problemset/all/

A list of questions that you'll fetch from an API and generate the list.
For now, use this API
https://leetcode.com/_next/data/Oh3lvYDA6G1um8iXOBYKB/problemset/all.json

For each question, the JSON will look as follows,
```
{
acRate: 32.70785540323679,
difficulty: "MEDIUM",
freqBar: null,
frontendQuestionId: "3",
isFavor: false,
paidOnly: false,
status: "NOT_STARTED",
title: "Longest Substring Without Repeating Characters",
titleSlug: "longest-substring-without-repeating-characters",
topicTags: [
{
name: "Hash Table",
id: "VG9waWNUYWdOb2RlOjY=",
slug: "hash-table"
},
{
name: "String",
id: "VG9waWNUYWdOb2RlOjEw",
slug: "string"
},
{
name: "Sliding Window",
id: "VG9waWNUYWdOb2RlOjU1ODIx",
slug: "sliding-window"
}
],
hasSolution: true,
hasVideoSolution: true
}
```

**Comment by yashtibrewal** [comment]
Hey @harlsh if we are designing the page https://leetcode.com/problemset/all/ , I am unable to make out how the API will help us, could you help me out please. 
Also, have you designed any database for the same? If not, I suggest, lets make one in a meet and then deliver the field names of the variables and "question" model so that its less work for the frontend guys later on to change things.

**Comment by erik-rosa** [comment]
Please change the name of this issue to **Implement All Problems List View**. @harlsh

**Comment by erik-rosa** [comment]
![image](https://user-images.githubusercontent.com/56844083/151427420-30805fbb-673d-4a56-a6d9-b5ccb0def101.png)

**Comment by harlsh** [comment]
@vijay-red You merged the code without any PR. Put some screenshots here of the UI before you merge it.

![image](https://user-images.githubusercontent.com/20385352/152473893-aeacaaaa-8e31-490a-86fc-67bc5f2dca37.png)

**Comment by erik-rosa** [comment]
redacted
